apiVersion: v1

kind: Service

metadata:

  name: my-clusterip-service

spec:

  type: ClusterIP

  clusterIP: 10.10.5.10

  ports:

 —name: http

    protocol: TCP

    port: 80

    targetPort: 8080
