apiVersion: v1

kind: Service

metadata:

  name: loadbalancer-service

spec:

  type: LoadBalancer

  clusterIP: 10.0.160.30

  selector:

    app: nginx

  ports:

 —name: http

    protocol: TCP

    port: 80

    targetPort: 8080
